---
- hosts: all
  tasks:     
  
    - name: Check RTL Agent is running
      shell: ps -ef | grep './agent.sh'
      register: result1
    - debug: msg={{ result1.stdout_lines }}

#    - name: Install libraries for RTL Agent
#      apt: pkg="{{ item }}"
#      become: yes
#      become_user: root
