---
- hosts: all
  tasks:     

    - name: Install RTL Agent
      apt:
        deb: "{{ deb_path }}"
      become: yes
      become_user: root
    
    - name: Remove .deb file
      shell: rm {{ deb_path }}
      register: result2
    - debug: msg={{ result2.stdout_lines }}
